$packageName = "LiveReloadWebServer"
$url = "https://github.com/RickStrahl/Westwind.AspnetCore.LiveReload/raw/0.2.4/LiveReloadServer/LiveReloadWebServer.zip"
$drop = "$(Split-Path -Parent $MyInvocation.MyCommand.Definition)"
$sha = "787BDA2C7B5056DC1ACDDA49C14DFA9EB58A255B5260CAEAC24F98981015DFB5"
Install-ChocolateyZipPackage -PackageName "$packageName" -Url "$url" -UnzipLocation "$drop" -checksum64 "$sha" -checksumtype "sha256"
